### ISSUE TITLE
SSL certificates expired

### ISSUE THREAD

**Issue by nikhil-sarin** [astrocatalogs/OACAPI#12]
The SSL certificate for the catalogs have expired. Is there any plan to renew them? The API no longer works with the certificates. The websites do not have to be rebuilt for it to work though so I was hoping just the certificate would get renewed.

**Comment by guillochon** [comment]
Apologies @nikhil-sarin, the certificates have been renewed.

**Comment by nikhil-sarin** [comment]
Thanks @guillochon!
