### ISSUE TITLE
OACPI is not available

### ISSUE THREAD

**Issue by hombit** [astrocatalogs/OACAPI#13]
Looks like OACPI web-server is in a bad state: all requests sent during last couple of days were time-outed:
```html
<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>
```

We at [SNAD team](https://snad.space) actively use OACPI as a part of the [ZTF DR viewer portal](https://ztf.snad.space) and very appreciate a huge work you made to collect and organize all these data. Is there something we can help with to make it back to live? Is it possible to run a mirror of the OACPI by someone else? I've looked briefly through the code and found that it requires some data I'm not sure how to get (like `catalog.min.json` files).

**Comment by guillochon** [comment]
Hi @hombit, I'm taking a look into it now.

**Comment by guillochon** [comment]
Should be working again.

As for mirrors of the OAC: there is an effort by Ashley Villar to launch an OAC 2.0 sometime in the future, but I don't have any details as I am not directly involved. I intend to keep this API functional until that happens, so please don't be shy in opening issues if the service isn't operating.

**Comment by hombit** [comment]
Thank you, it works again!
