### ISSUE TITLE
Service not responding

### ISSUE THREAD

**Issue by br155bundi** [astrocatalogs/OACAPI#14]
Hello, I have been trying to extract some kne data and it seems that the API will not connect. Is this an issue you are aware of, it could be my end.

**Comment by guillochon** [comment]
Hi, you must use the astrocats.space for API calls from now on, all other domains have been disabled.

**Comment by nikhil-sarin** [comment]
Not sure if this is the same issue but the readme examples don't work, and they appear to be using the astrocats.space - e.g., https://api.astrocats.space/SN2014J/photometry/magnitude+e_magnitude+band 

will open a page with this error. 
{"message": "Event 'photometry' not found in any catalog."}

**Comment by guillochon** [comment]
Hi @nikhil-sarin, I see the same issue. Working on it, will keep you posted.

**Comment by guillochon** [comment]
Should be fixed. We recently changed domain name providers and it caused a bunch of issues the past few weeks, I think I finally figured it out though.
