### ISSUE TITLE
SSL certificate verification error

### ISSUE THREAD

**Issue by bsipocz** [astrocatalogs/OACAPI#16]
I'm running into some SSL verification errors again with the astroquery test suite, could you please have a look if they are indeed expired or there are some other errors? Thanks!

```
UNEXPECTED EXCEPTION: SSLError(MaxRetryError("HTTPSConnectionPool(host='api.astrocats.space', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1000)')))"))
```

**Comment by guillochon** [comment]
Hi Brigitta, sorry about that...should be updated now.

Best,
James

**Comment by bsipocz** [comment]
Thank you so much, all tests pass now.
